# File: .github/workflows/repo-sync.yml

on: 
  push:
    branches: [ development ]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    #steps:
    #- name: repo-sync-lms
    #  uses: wei/git-sync@v2
    #  with:
    #    source_repo: "git@github.com:murad357/parent-repo.git"
    #    source_branch: "development"
    #    destination_repo: "git@github.com:murad357/child-repo1.git"
    #    destination_branch: "development"
    #    ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: repo-sync
        uses: wei/git-sync@d4bce1c
        with:
          source_repo: "murad357/parent-repo.git"
          source_branch: "development"
          destination_repo: "git@github.com:murad357/repository.git"
          destination_branch: "development"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`